eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: eureka-zuul
zuul:
  routes:
    api-a:
      path: /feign/**
      serviceId: eureka-feign
    api-b:
      path: /hystrix/**
      serviceId: eureka-feign-hystrix

